import './js/CocktailsApiService';
import './js/randomCocktailsCards';
import './js/cocktailByLetter';
import './js/headerMain';
import './js/changeOfSubject';
import './js/modalMobile';
import './js/searchHeader';
import './js/cocktailNotFound';
import './js/firebase';
import './js/heroButtonChange';
import './js/modalCocktails';
import './js/modalIngredients';
import './js/searchMobileMain'